[package]
name = "blog_new"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.19"
#toml解析
toml = "0.8.14"
serde = "1.0.203"
serde_derive = "1.0.136"
config = "0.14.0"
#日志
humantime = "2.1.0"
log = "0.4"
fern = "0.6"
